### ISSUE TITLE
Line #6 in msgbuilder.ts return key as list of array and line #7 need to be [for...of] loop

### ISSUE THREAD

**Issue by skingsly** [albertleigh/redux-solace#1]
Const keys = sdtMapContainer ? **sdtMapContainer.getKeys()** : {};
for (let key **in** keys) {

@albertleigh - Is this issue can be fixed anytime soon?

**Comment by albertleigh** [comment]
sure, sorry for the late respponse; i can do it with in a day or two and pr is also welcome; btw did you have a test env? solace corp no longer provided me a test env, that's why i left it as it was for a long long time

**Comment by albertleigh** [comment]
hi skingsly~ could u try redux-solace@0.20.21-next.0 and let me know and feel free to fork from develop~ thks

**Comment by skingsly** [comment]
@albertleigh - sure. I can test new version. Can you let me know if its created(@0.20.21-next.0)? I dont find it.

**Comment by albertleigh** [comment]
> there u go https://www.npmjs.com/package/redux-solace/v/0.20.21-next.0 @skingsly

**Comment by skingsly** [comment]
@albertleigh - its working as expected. Thank you for fixing the issue.

**Comment by albertleigh** [comment]
@skingsly, so what is the cause? is it b/c solace.js released some new wrapper for SDTMap deserializer? I would like to put it into the changelog of the next release

**Comment by skingsly** [comment]
@albertleigh ok sure. I can help.

May be SDTMap got updated. getKeys() function return keys in array of string.
